# Generated by Django 3.0.8 on 2020-07-12 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('computer', 'کامپوتر ترم 1'), ('Electricity2', 'برق ترم 2'), ('Mec1', 'مکانیک ترم 1'), ('Mec2', 'مکانیک ترم 2')], max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('id_num', models.IntegerField()),
                ('academic_rank', models.CharField(max_length=30)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.Field')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('id_num', models.IntegerField(unique=True)),
                ('number_of_unit', models.IntegerField()),
                ('grade', models.CharField(max_length=30)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='portalapp.Field')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('id_number', models.IntegerField()),
                ('number_of_unit', models.IntegerField()),
                ('number_of_student', models.IntegerField()),
                ('students', models.ManyToManyField(to='portalapp.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.Teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.Field')),
            ],
        ),
    ]
